---
output:
  word_document: default
  html_document: default
---
# GIS for Transport Applications (GIS4TA)

# Overview

GIS4TA is a free-to-attend workshop about the emerging field of geospatial methods for transport research.
The *second ever* GIS4TA will take place on Thursday and Friday **16^th^ - 17^th^ November 2017** (start date: [`2017-11-16`](https://jsfiddle.net/zygs3rLn/)).
It was originally held as a 1 day event that preceded the GISRUK 2015 conference.
This was an overwhelming success, with 20+ attendees and much positive feedback after the event.
At the GISRUK 2017 conference in Manchester, it was agreed that there should be a full 2 day conference on the topic.
It is sponsored by the Royal Geographic Society (RGS) via the Transport Geography Research Group (TGRG), with support from the Leeds Institute for Data Analytics (LIDA) and the Institute for Transport Studies (ITS).

We plan for a relatively small (~30 people) but high impact conference at the cutting edge of geographical data analysis for transport policy.

# Aim and objectives

 The aim is to share knowledge, skills and ideas around the application of geospatial data to address urgent transport and urban planning problems.
By the end of the workshop, all participants should be better answer many questions in this area, including:

- What is the 'landscape' of tools and software projects in the space of GIS4TA?
- How to effectively handle large transport datasets?
- Where to locate new transport infrastructure? 
- How to develop automated and reproducible transport planning workflows?
- How can increasingly available datasets on air quality, traffic and active travel be used to inform policy?
- How to visualise results in an attractive and potentially on-line and interactive manner?
- How can geospatial methods be used to create local evidence bases needed to transition away from fossil fuels in the transport sector?

# Agenda

Day 1:

- Introduction and overview of GIS for transport
- R for Transport applications (RL)
- Car fleet data (CM)
- OTP Tutuorial (MY)
- Minihack 1

Day 2:

- Lightning talks
- OSM for Transport applications (MP)
- Microsimulation tutorial (AS)
- Minihack and free working


# How to apply

To apply, first sign-up for a free ticket on the Eventbrite page.

You should also write a short (max: 100 words) statement explaining why you would like to participate in the event, containing something on how you will gain, and what you can contribute.
There are 2 ways you can send this:

1. Via the eventbrite page: https://www.eventbrite.co.uk/e/gis-for-transport-applications-tickets-38491819067

1. Via a [pull request](https://help.github.com/articles/about-pull-requests/) adding a file with your name (e.g. [`robinlovelace.md`](https://github.com/Robinlovelace/GIS4TA/blob/master/participants/robinlovelace.md)) to the [`participants`](https://github.com/Robinlovelace/GIS4TA/tree/master/participants) folder in the https://github.com/Robinlovelace/GIS4TA GitHub repository (preferred)

If more than 20 people sign-up we will rank the applications anonymously based on the abstract.

# Call for maps

Instead of the traditional 'Call for Papers', this event calls for maps that people have made. 
These optional maps can include static images, online maps or even interactive online visualisations. Entrants will be given a 5 minute slot to describe their map and its purpose in a session before lunch.
The best map will be decided by a panel of judges in terms of originality and potential impact.
The winner will a free book and attendance to training courses.
